
["Gore Edition"]
	#Toggle if spawn structures, mobs, etc. (default is all in false)
	toggle_gore_edition_content = false
	#Toggle if spawn experiments mobs
	gore_edition_experiments = false
	#Toggle if traps can be crafted
	traps = false
	#Toggle if send weapons creations messages to the chat
	gore_edition_weapons_creations_messages_to_chat = true

["Gore config"]
	#Recomended 0,5 to 3
	gore_amount = 1.0
	#Recomended 0.25 to 0.5
	gore_velocity = 0.4
	#(Toggle the chance of surviving, resurrected, and corpse mobs spawning). 0 is never, 1 is always, 2 is 50/50
	survivors_and_corpses = 2.0
	#(Toggle if appears survivors or corpses, or the two). 0 is corpses, 1 is survivors or resurrecteds, 2 is the two
	survivors_or_corpses = 2.0

["Other config"]
	#Toggle if resurrected/survivors burns in the sunlight
	survivors_burn = true

